# -*- coding: utf-8 -*-
"""12-16

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eDdG55meBkPnfpGS64LM6tSLFbTUtp9U
"""

pip install openai

import openai
# OpenAI API 키 설정
openai.api_key = '  '

def summarize_text(text, max_tokens=150):
    """
    텍스트를 요약하는 함수

    :param text: 요약할 텍스트
    :param max_tokens: 요약된 텍스트의 최대 토큰 수
    :return: 요약된 텍스트
    """
    response = openai.completions.create
    (
        model="text-davinci-003",  # 현재 사용 가능한 엔진 중에서 선택
        prompt=sample_text,
        max_tokens=max_tokens,
        temperature=0.5,  # 낮을수록 더 확정적인 답변을 생성합니다.
        stop=None  # 문장의 끝을 감지하기 위한 키워드 설정
    )

    summary = response.choices[0].text.strip()
    return summary

# 텍스트 요약을 테스트할 샘플 텍스트
sample_text = """

"""

# 텍스트 요약 함수 호출
result_summary = summarize_text(sample_text)

# 결과 출력
print("원본 텍스트:\n", sample_text)
print("\n요약된 텍스트:\n", result_summary)

from openai import OpenAI
client = OpenAI(api_key = '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')

response = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {
      "role": "system",
      "content": "/content/drive/MyDrive/121311.jsonl"
    },

  ],
  temperature=0,
  max_tokens=1300,
  top_p=1
)

from google.colab import drive
drive.mount('/content/drive')