# -*- coding: utf-8 -*-
"""링크 및 제목 가져오기ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHXK9xKCGdPPzhYWl2DzRzCSX68UZ6j3
"""

from requests import get
from json import loads

def crawling_nexon_news():
    url = "https://forum.nexon.com/api/v1/board/1018/threads?alias=bluearchive&pageNo=1&paginationType=PAGING&pageSize=15&blockSize=5&_=1700919768522"
    r = get(url)

    js = loads(r.text)
    dic = {}
    url2 = "https://forum.nexon.com/bluearchive/board_view?board=1018&thread="

    for i in range(15):
        dic[url2 + js["threads"][i]["threadId"]] = js["threads"][i]["title"]

    return dic

print(crawling_nexon_news())